### ISSUE TITLE
How Do I Download The Mod??????

### ISSUE THREAD

**Issue by DEMnetwork** [LepkoQQ/Recycler#7]
I Didn't Saw A Release At The Realeses Page Of Github So I Can Download The Compiled Files

**Comment by coolsimulations** [comment]
The mod didn't even work in the first place, but here's the link:
https://www.curseforge.com/minecraft/mc-mods/recycler

**Comment by DEMnetwork** [comment]
But The Owner Should Make It DOwnloadble At Github Releases
